// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6ZpXKZQqHFrYLSVkj6t7xOiXLJoOKE_Q',
    appId: '1:969316193926:web:75a0fd2e24f7744eeae307',
    messagingSenderId: '969316193926',
    projectId: 'alter-ed043',
    authDomain: 'alter-ed043.firebaseapp.com',
    storageBucket: 'alter-ed043.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB32t1Ig9Vvfx4YcF1HXOLNoa8njKCccsI',
    appId: '1:969316193926:android:e83676df3ff259b7eae307',
    messagingSenderId: '969316193926',
    projectId: 'alter-ed043',
    storageBucket: 'alter-ed043.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUj_ArGKlM3BPT_0iWpqNBJ722FFjvbaU',
    appId: '1:969316193926:ios:2e6b06511143c1f3eae307',
    messagingSenderId: '969316193926',
    projectId: 'alter-ed043',
    storageBucket: 'alter-ed043.appspot.com',
    iosBundleId: 'com.raymond.alter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUj_ArGKlM3BPT_0iWpqNBJ722FFjvbaU',
    appId: '1:969316193926:ios:891b27776c16b92eeae307',
    messagingSenderId: '969316193926',
    projectId: 'alter-ed043',
    storageBucket: 'alter-ed043.appspot.com',
    iosBundleId: 'com.raymond.alter.RunnerTests',
  );
}
